module.exports = {
  someSidebar: {
    TILs: [
      'tils/index',
      {
        Terminals: ['tils/terminals/alt-click']
      }
    ],
    Cheatsheets: [
      {
        type: 'autogenerated',
        dirName: 'cheatsheets'
      }
    ]
  }
}
