module.exports = {
  tils: [{ type: 'autogenerated', dirName: 'tils' }],
  // cheatsheets: [{ type: 'autogenerated', dirName: 'notes/cheatsheets' }],
  notes: [{ type: 'autogenerated', dirName: 'notes' }],
  finds: [{ type: 'autogenerated', dirName: 'finds' }]
}
