import { useEffect } from 'react'

const useScript = () => {
  useEffect(() => {
    const script = document.createElement('script')
    script.innerText = `
    /*
     Copyright and licenses see https://www.dynatrace.com/company/trust-center/customers/reports/*/
    (function(){"undefined"!==typeof window&&window.setTimeout&&(window.setTimeout=window.setTimeout);this.dT_&&dT_.prm&&dT_.prm();(function(){function va(){document.cookie="__dTCookie=1;SameSite=Lax";var bb=-1!==document.cookie.indexOf("__dTCookie");document.cookie="__dTCookie=1; expires=Thu, 01-Jan-1970 00:00:01 GMT";return bb}function Qa(){return void 0===lb.dialogArguments?navigator.cookieEnabled||va():va()}function Ja(){var bb;if(Qa()&&!window.dT_){var Ka=(bb={},bb.cfg="app=4b6329f719b105fd|cors=1|rcdec=1209600000|featureHash=A2Vfqru|vcv=2|reportUrl=https://bf48922oxv.bf.dynatrace.com/bf|rdnt=1|uxrgce=1|bp=3|srmcrv=10|cuc=0jznftah|mel=100000|dpvc=1|ssv=4|lastModification=1644906062376|dtVersion=10233220201140653|srmcrl=1|tp=500,50,0,1|uxdcw=1500|featureHash=A2Vfqru|agentUri=https://js-cdn.dynatrace.com/jstag/16362cc0dec/ruxitagent_A2Vfqru_10233220201140653.js|auto=|domain=|rid=RID_|rpid=|app=4b6329f719b105fd",
    bb.iCE=Qa,bb);window.dT_=Ka}}var lb="undefined"!==typeof window?window:self,Wa;lb.dT_?(null===(Wa=lb.console)||void 0===Wa?void 0:Wa.log("Duplicate agent injection detected, turning off redundant initConfig."),lb.dT_.di=1):Ja()})()})();
    /*
     Copyright and licenses see https://www.dynatrace.com/company/trust-center/customers/reports/*/
    (function(){"undefined"!==typeof window&&window.setTimeout&&(window.setTimeout=window.setTimeout);this.dT_&&dT_.prm&&dT_.prm();(function(){function va(k,u,M){void 0===M&&(M=0);var la=-1;u&&(null===k||void 0===k?0:k.indexOf)&&(la=k.indexOf(u,M));return la}function Qa(){var k;return!(null===(k=v.console)||void 0===k||!k.log)}function Ja(k,u){if(!u)return"";var M=k+"=";k=va(u,M);if(0>k)return"";for(;0<=k;){if(0===k||" "===u.charAt(k-1)||";"===u.charAt(k-1))return M=k+M.length,k=va(u,";",k),0<=k?u.substring(M,
    k):u.substr(M);k=va(u,M,k+M.length)}return""}function lb(k){return Ja(k,document.cookie)}function Wa(){}function bb(){var k=0;try{k=Math.round(v.performance.timeOrigin)}catch(u){}if(0>=k||isNaN(k)||!isFinite(k)){k=0;try{k=v.performance.timing.navigationStart}catch(u){}k=0>=k||isNaN(k)||!isFinite(k)?B.dT_.gAST():k}Aa=k;cb=Ka;return Aa}function Ka(){return Aa}function xa(){return cb()}function fb(){var k,u=0;if(null===(k=null===v||void 0===v?void 0:v.performance)||void 0===k?0:k.now)try{u=Math.round(v.performance.now())}catch(M){}return 0>=
    u||isNaN(u)||!isFinite(u)?(new Date).getTime()-cb():u}function ba(k,u){void 0===u&&(u=document.cookie);return Ja(k,u)}function Y(){}function Da(k,u){return function(){k.apply(u,arguments)}}function ja(k){if(!(this instanceof ja))throw new TypeError("Promises must be constructed via new");if("function"!==typeof k)throw new TypeError("not a function");this.da=0;this.Xa=!1;this.ga=void 0;this.ja=[];La(k,this)}function ua(k,u){for(;3===k.da;)k=k.ga;0===k.da?k.ja.push(u):(k.Xa=!0,ja.Aa(function(){var M=
    1===k.da?u.ac:u.bc;if(null===M)(1===k.da?Ia:Ra)(u.promise,k.ga);else{try{var la=M(k.ga)}catch(pb){Ra(u.promise,pb);return}Ia(u.promise,la)}}))}function Ia(k,u){try{if(u===k)throw new TypeError("A promise cannot be resolved with itself.");if(u&&("object"===typeof u||"function"===typeof u)){var M=u.then;if(u instanceof ja){k.da=3;k.ga=u;pa(k);return}if("function"===typeof M){La(Da(M,u),k);return}}k.da=1;k.ga=u;pa(k)}catch(la){Ra(k,la)}}function Ra(k,u){k.da=2;k.ga=u;pa(k)}function pa(k){2===k.da&&0===
    k.ja.length&&ja.Aa(function(){k.Xa||ja.$a(k.ga)});for(var u=0,M=k.ja.length;u<M;u++)ua(k,k.ja[u]);k.ja=null}function W(k,u,M){this.ac="function"===typeof k?k:null;this.bc="function"===typeof u?u:null;this.promise=M}function La(k,u){var M=!1;try{k(function(la){M||(M=!0,Ia(u,la))},function(la){M||(M=!0,Ra(u,la))})}catch(la){M||(M=!0,Ra(u,la))}}function ia(){Jb.Aa=function(k){if("string"===typeof k)throw Error("Promise polyfill called _immediateFn with string");k()};Jb.$a=function(){};return Jb}function O(k,
    u){return parseInt(k,u||10)}function Pa(k){return document.getElementsByTagName(k)}function L(k){var u=k.length;if("number"===typeof u)k=u;else{u=0;for(var M=2048;k[M-1];)u=M,M+=M;for(var la=7;1<M-u;)la=(M+u)/2,k[la-1]?u=la:M=la;k=k[la]?M:u}return k}function H(k){for(var u=[],M=1;M<arguments.length;M++)u[M-1]=arguments[M];k.push.apply(k,u)}function E(k){k=encodeURIComponent(k);var u=[];if(k)for(var M=0;M<k.length;M++){var la=k.charAt(M);H(u,Tb[la]||la)}return u.join("")}function S(k){-1<va(k,"^")&&
    (k=k.split("^^").join("^"),k=k.split("^dq").join('"'),k=k.split("^rb").join(">"),k=k.split("^lb").join("<"),k=k.split("^p").join("|"),k=k.split("^e").join("="),k=k.split("^s").join(";"),k=k.split("^c").join(","),k=k.split("^bs").join("\\"));return k}function ma(k,u){if(!k||!k.length)return-1;if(k.indexOf)return k.indexOf(u);for(var M=k.length;M--;)if(k[M]===u)return M;return-1}function R(k,u){void 0===u&&(u=[]);if(!k||"object"!==typeof k&&"function"!==typeof k)return!1;var M="number"!==typeof u?u:
    [],la=null,pb=[];switch("number"===typeof u?u:5){case 0:la="Array";pb.push("push");break;case 1:la="Boolean";break;case 2:la="Number";break;case 3:la="String";break;case 4:la="Function";break;case 5:la="Object";break;case 6:la="Date";pb.push("getTime");break;case 7:la="Error";pb.push("name","message");break;case 8:la="Element";break;case 9:la="HTMLElement";break;case 10:la="HTMLImageElement";pb.push("complete");break;case 11:la="PerformanceEntry";break;case 12:la="PerformanceTiming";break;case 13:la=
    "PerformanceResourceTiming";break;case 14:la="PerformanceNavigationTiming";break;case 15:la="CSSRule";pb.push("cssText","parentStyleSheet");break;case 16:la="CSSStyleSheet";pb.push("cssRules","insertRule");break;case 17:la="Request";pb.push("url");break;case 18:la="Response";pb.push("ok","status","statusText");break;case 19:la="Set";pb.push("add","entries","forEach");break;case 20:la="Map";pb.push("set","entries","forEach");break;case 21:la="Worker";pb.push("addEventListener","postMessage","terminate");
    break;case 22:la="XMLHttpRequest";pb.push("open","send","setRequestHeader");break;case 23:la="SVGScriptElement";pb.push("ownerSVGElement","type");break;case 24:la="HTMLMetaElement";pb.push("httpEquiv","content","name");break;case 25:la="HTMLHeadElement";break;case 26:la="ArrayBuffer";break;case 27:la="ShadowRoot",pb.push("host","mode")}u=la;if(!u)return!1;pb=pb.length?pb:M;if(!M.length)try{if(v[u]&&k instanceof v[u]||Object.prototype.toString.call(k)==="[object "+u+"]")return!0}catch(Kb){}for(M=0;M<
    pb.length;M++)if(u=pb[M],"string"!==typeof u&&"number"!==typeof u&&"symbol"!==typeof u||!(u in k))return!1;return!!pb.length}function qa(k,u,M,la){"undefined"===typeof la&&(la=Ya(u,!0));"boolean"===typeof la&&(la=Ya(u,la));if(k===v)Ob?Ob(u,M,la):qd&&qd("on"+u,M);else if(Id&&R(k,21))Yc.call(k,u,M,la);else if(k.addEventListener)if(k===v.document||k===v.document.documentElement)Hc.call(k,u,M,la);else try{Ob.call(k,u,M,la)}catch(zc){k.addEventListener(u,M,la)}else k.attachEvent&&k.attachEvent("on"+u,
    M);la=!1;for(var pb=ld.length;0<=--pb;){var Kb=ld[pb];if(Kb.object===k&&Kb.event===u&&Kb.Y===M){la=!0;break}}la||B.dT_.apush(ld,{object:k,event:u,Y:M})}function Ha(k,u,M,la){for(var pb=ld.length;0<=--pb;){var Kb=ld[pb];if(Kb.object===k&&Kb.event===u&&Kb.Y===M){ld.splice(pb,1);break}}"undefined"===typeof la&&(la=Ya(u,!0));"boolean"===typeof la&&(la=Ya(u,la));k===v?cc?cc(u,M,la):qd&&qd("on"+u,M):k.removeEventListener?k===v.document||k===v.document.documentElement?Dd.call(k,u,M,la):cc.call(k,u,M,la):
    k.detachEvent&&k.detachEvent("on"+u,M)}function Ya(k,u){var M=!1;try{if(Ob&&-1<ma(If,k)){var la=Object.defineProperty({},"passive",{get:function(){M=!0}});Ob("test",Wa,la)}}catch(pb){}return M?{passive:!0,capture:u}:u}function Ib(){for(var k=ld,u=k.length;0<=--u;){var M=k[u];Ha(M.object,M.event,M.Y)}ld=[]}function kb(k,u,M){if(M||2===arguments.length)for(var la=0,pb=u.length,Kb;la<pb;la++)!Kb&&la in u||(Kb||(Kb=Array.prototype.slice.call(u,0,la)),Kb[la]=u[la]);return k.concat(Kb||Array.prototype.slice.call(u))}
    function ca(k){return"function"===typeof k&&/{\s+\[native code]/.test(Function.prototype.toString.call(k))}function ra(k,u){for(var M,la=[],pb=2;pb<arguments.length;pb++)la[pb-2]=arguments[pb];return void 0!==Function.prototype.bind&&ca(Function.prototype.bind)?(M=Function.prototype.bind).call.apply(M,kb([k,u],la,!1)):function(){for(var Kb=0;Kb<arguments.length;Kb++);return k.apply(u,(la||[]).concat(Array.prototype.slice.call(arguments)||[]))}}function V(){if(He){var k=new He;if(qe)for(var u=0,M=
    ef;u<M.length;u++){var la=M[u];void 0!==qe[la]&&(k[la]=ra(qe[la],k))}return k}return $c?new $c("MSXML2.XMLHTTP.3.0"):v.XMLHttpRequest?new v.XMLHttpRequest:new v.ActiveXObject("MSXML2.XMLHTTP.3.0")}function na(){document.cookie="__dTCookie=1;SameSite=Lax";var k=-1!==document.cookie.indexOf("__dTCookie");document.cookie="__dTCookie=1; expires=Thu, 01-Jan-1970 00:00:01 GMT";return k}function Ua(){return void 0===v.dialogArguments?navigator.cookieEnabled||na():na()}function qb(){return 0<=va(navigator.userAgent,
    "RuxitSynthetic")}function tb(){return Mc}function nb(k){Mc=k}function Bb(k){var u=fa("rid"),M=fa("rpid");u&&(k.rid=u);M&&(k.rpid=M)}function ec(k){if(k=k.xb){k=S(k);try{Mc=new RegExp(k,"i")}catch(u){}}else Mc=void 0}function Ub(k){return"n"===k||"s"===k||"l"===k?";SameSite="+ye[k]:""}function Ba(k,u,M){var la=1,pb=0;do document.cookie=k+'=""'+(u?";domain="+u:"")+";path="+M.substr(0,la)+"; expires=Thu, 01 Jan 1970 00:00:01 GMT;",la=M.indexOf("/",la),pb++;while(-1!==la&&5>pb)}function Gb(k){var u=
    {},M=0;for(k=k.split("|");M<k.length;M++){var la=k[M].split("=");2===la.length&&(u[la[0]]=decodeURIComponent(la[1].replace(/\+/g," ")))}return u}function wb(){var k=fa("csu");return(k.indexOf("dbg")===k.length-3?k.substr(0,k.length-3):k)+"_"+fa("app")+"_Store"}function Z(k,u,M){void 0===u&&(u={});var la=0;for(k=k.split("|");la<k.length;la++){var pb=k[la],Kb=pb,zc=va(pb,"=");-1===zc?u[Kb]="1":(Kb=pb.substring(0,zc),u[Kb]=pb.substring(zc+1,pb.length))}!M&&(M=u,la=M.spc)&&(k=document.createElement("textarea"),
    k.innerHTML=la,M.spc=k.value);return u}function ab(k){var u;return null!==(u=uc[k])&&void 0!==u?u:md[k]}function Ma(k){k=ab(k);return"false"===k||"0"===k?!1:!!k}function Q(k){var u=ab(k);u=O(u);isNaN(u)&&(u=md[k]);return u}function fa(k){return String(ab(k)||"")}function wa(k,u){uc[k]=String(u)}function Za(k){return uc=k}function Eb(k){uc[k]=0>va(uc[k],"#"+k.toUpperCase())?uc[k]:""}function pc(k){var u=k.agentUri;u&&-1<va(u,"_")&&(u=/([a-zA-Z]*)[0-9]{0,4}_([a-zA-Z_0-9]*)_[0-9]+/g.exec(u))&&u.length&&
    2<u.length&&(k.csu=u[1],k.featureHash=u[2])}function Fb(k){var u=k.domain||"";var M=(M=location.hostname)&&u?M===u||-1!==M.indexOf("."+u,M.length-("."+u).length):!0;if(!u||!M){k.domainOverride||(k.domainOverride=location.hostname+","+u,delete k.domain);var la=fa("cssm");var pb=document.domain||"";if(pb){pb=pb.split(".").reverse();var Kb=pb.length;if(1>=Kb)la="";else{for(var zc=pb[0],Ec="",Jc=1;Jc<=Kb;Jc++)if(ba("dTValidationCookie")){Ec=zc;break}else{pb[Jc]&&(zc=pb[Jc]+"."+zc);var od="dTValidationCookie=dTValidationCookieValue;path=/;domain="+
    zc;od+=Ub(la);document.cookie=od}Ba("dTValidationCookie",Ec,"/");la=Ec}}else la="";la&&(k.domain=la);M||H(ff,{type:"dpi",severity:"Warning",text:'Configured domain "'+u+'" is invalid for current location "'+location.hostname+'". Agent will use "'+k.domain+'" instead.'})}}function N(k,u){Fb(k);uc.pVO&&(k.pVO=uc.pVO);u||(u=k.bp||md.bp,k.bp2&&(u=2),k.bp=String(u))}function w(){return uc}function F(k){return md[k]===ab(k)}function q(){if(v.MobileAgent||v.dynatraceMobile){var k=lb("dtAdkSettings");return B.dT_.p3SC(k).privacyState||
    null}return null}function J(){var k=q();return 2===k||1===k?!1:!B.dT_.bcv("coo")||B.dT_.bcv("cooO")||qb()}function z(k,u){return!J()||v.dT_.overloadPrevention&&!qb()?null:k.apply(this,u||[])}function ea(k,u){try{var M=zd;M&&M.setItem(k,u)}catch(la){}}function P(k,u){z(ea,[k,u])}function aa(k){try{var u=zd;if(u)return u.getItem(k)}catch(M){}return null}function U(k){try{var u=zd;u&&u.removeItem(k)}catch(M){}}function Ga(k){return 32===k.length||12>=k.length?k:""}function gb(k){k=k.replace("-2D","-");
    if(!isNaN(Number(k))){var u=O(k);if(-99<=u&&99>=u)return k}return""}function ob(k){var u={sessionId:"",serverId:"",overloadState:0},M=va(k,"|"),la=k;-1!==M&&(la=k.substring(0,M));M=va(la,"$");-1!==M?(u.sessionId=Ga(la.substring(M+1)),u.serverId=gb(la.substring(0,M))):u.sessionId=Ga(la);return u}function xb(k){var u={sessionId:"",serverId:"",overloadState:0},M=k.split("v"===k.charAt(0)?"_":"=");if(2<M.length&&0===M.length%2){k=Number(M[1]);if(isNaN(k)||3>k)return u;k={};for(var la=2;la<M.length;la++)k[M[la]]=
    M[la+1],la++;u.sessionId=k.sn?Ga(k.sn):"hybrid";k.srv&&(u.serverId=gb(k.srv));M=Number(k.ol);if(1===M){la=qb();var pb=v.dT_;la||(P("dtDisabled","true"),pb.disabled=!0,pb.overloadPrevention=!0)}0<=M&&2>=M&&(u.overloadState=M);k=Number(k.prv);isNaN(k)||(u.privacyState=1>k||4<k?1:k)}return u}function Nb(){return Wd()}function $b(k,u){function M(){delete Jf[Kb];k.apply(this,arguments)}for(var la=[],pb=2;pb<arguments.length;pb++)la[pb-2]=arguments[pb];if("apply"in nh){la.unshift(M,u);var Kb=nh.apply(v,
    la)}else Kb=nh(M,u);Jf[Kb]=!0;return Kb}function Yb(k){delete Jf[k];"apply"in Oe?Oe.call(v,k):Oe(k)}function Vb(k){H(re,k)}function kc(k){for(var u=re.length;u--;)if(re[u]===k){re.splice(u,1);break}}function dd(){return re}function ic(k,u){return Zg(k,u)}function Zc(k){Tf(k)}function oa(k,u){if(!af||!Xi)return"";k=new af([k],{type:u});return Xi(k)}function ya(k,u){return ke?new ke(k,u):void 0}function Sa(k){"function"===typeof k&&H(nf,k)}function db(){return nf}function Cb(){return Jh}function Qb(k){return function(){for(var u=
    [],M=0;M<arguments.length;M++)u[M]=arguments[M];if("number"!==typeof u[0]||!Jf[u[0]])try{return k.apply(this,u)}catch(la){return k(u[0])}}}function Oa(){return ff}function Ac(){cb=bb;v.performance&&(Wd=function(){return Math.round(cb()+fb())});if(!Wd||isNaN(Wd())||0>=Wd()||!isFinite(Wd()))Wd=function(){return(new Date).getTime()}}function vc(){Pe&&(v.clearTimeout=Oe,v.clearInterval=Tf,Pe=!1)}function Tc(k,u){try{v.localStorage&&v.localStorage.setItem(k,u)}catch(M){}}function Bc(k){try{v.localStorage&&
    v.localStorage.removeItem(k)}catch(u){}}function Rc(){Bc("rxec");Bc("rxvisitid");Bc("rxvt")}function Cc(k){document.cookie=k+'="";path=/'+(fa("domain")?";domain="+fa("domain"):"")+"; expires=Thu, 01 Jan 1970 00:00:01 GMT;"}function mc(k,u,M,la){le=!0;u||0===u?(u=String(u).replace(/[;\n\r]/g,"_"),k=k+"="+u+";path=/"+(fa("domain")?";domain="+fa("domain"):""),M&&(k+=";expires="+M.toUTCString()),k+=Ub(fa("cssm")),la&&"https:"===location.protocol&&(k+=";Secure"),document.cookie=k):Cc(k);le=!1}function fd(k,
    u,M,la){z(mc,[k,u,M,la])}function Nc(k){return 2<(null===k||void 0===k?void 0:k.split("$").length)?!1:/^[0-9A-Za-z_=:$+\/.\-*%|]*$/.test(k)}function qc(k){k=ba("dtCookie",k);k||((k=aa("dtCookie"))&&Nc(k)?Qd(k):k="");return Nc(k)?k:""}function Qd(k){fd("dtCookie",k,void 0,Ma("ssc"))}function Kd(k){J()?k():(Ed||(Ed=[]),H(Ed,k))}function rc(k){return z(k)}function Dc(){if(Ma("coo")&&!J()){for(var k=0,u=Ed;k<u.length;k++)$b(u[k],0);Ed=[];wa("cooO",!0)}}function Ic(){if(Ma("coo")&&J()){wa("cooO",!1);Cc("dtCookie");
    Cc("dtPC");Cc("dtLatC");Cc("dtSa");Cc("dtAdk");Cc("rxVisitor");Cc("rxvt");try{U("rxec");U("rxvisitid");U("rxvt");Rc();var k=zd;k&&(k.removeItem("rxVisitor"),k.removeItem("dtCookie"));if(k=Hg)k.removeItem(wb()),k.removeItem("dtAdk")}catch(u){}}}function bc(k,u){void 0===u&&(u=document.cookie||"");return u.split(k+"=").length-1}function wc(k,u){var M=bc(k,u);if(1<M){u=fa("domain")||v.location.hostname;var la=v.location.hostname,pb=v.location.pathname,Kb=0,zc=0;ue.push(k);do{var Ec=la.substr(Kb);if(Ec!==
    u||"/"!==pb){Ba(k,Ec===u?"":Ec,pb);var Jc=bc(k);Jc<M&&(ue.push(Ec),M=Jc)}Kb=la.indexOf(".",Kb)+1;zc++}while(0!==Kb&&10>zc&&1<M);fa("domain")&&1<M&&Ba(k,"",pb)}}function Xd(){var k=document.cookie;wc("dtPC",k);wc("dtCookie",k);wc("dtLatC",k);wc("rxvt",k);0<ue.length&&H(ff,{severity:"Error",type:"dcn",text:"Duplicate cookie name"+(1!==ue.length?"s":"")+" detected: "+ue.join(", ")});Vb(function(u,M,la,pb){0<ue.length&&!M&&(u.av(pb,"dCN",ue.join(",")),ue=[]);0<tg.length&&!M&&(u.av(pb,"eCC",tg.join(",")),
    tg=[])})}function sc(k){var u=k,M=Math.pow(2,32);return function(){u=(1664525*u+1013904223)%M;return u/M}}function wd(k,u){return isNaN(k)||isNaN(u)?Math.floor(33*Kf()):Math.floor(Kf()*(u-k+1))+k}function Ld(k){if(!k)return"";var u=v.crypto||v.msCrypto;if(u&&-1===va(navigator.userAgent,"Googlebot"))u=u.getRandomValues(new Uint8Array(k));else{u=[];for(var M=0;M<k;M++)u.push(wd(0,32))}k=[];for(M=0;M<u.length;M++){var la=Math.abs(u[M]%32);k.push(String.fromCharCode(la+(9>=la?48:55)))}return k.join("")}
    function Ve(){return ug}function Ee(k){k&&(null===k||void 0===k?0:k.configurable)&&k.set&&k.get&&Object.defineProperty(document,"cookie",{get:function(){return k.get.call(document)},set:function(u){var M=u.split("=")[0];k.set.call(document,u);le?1<bc(M)&&ue.push(M):-1<ma(Lf,M)&&(tg.push(M),-1===ma(We,M)&&(H(We,M),H(ff,{severity:"Error",type:"ecm",text:"Invalid modification of agent cookie "+M+" detected. Modifying Dynatrace cookies may result in missing or invalid data."})))}})}function $d(k){void 0===
    k&&(k=!0);Ig=k}function Nd(k){if(k=k||qc()){var u=k.charAt(0);return"v"===u||"="===u?xb(k):ob(k)}return{sessionId:"",serverId:"",overloadState:0}}function lc(k){return Nd(k).serverId}function Jd(k){return Nd(k).sessionId}function id(k,u,M){var la=Q("pcl");la=k.length-la;0<la&&k.splice(0,la);la=lc(ba("dtCookie",M));for(var pb=[],Kb=la?la+"$":"",zc=0;zc<k.length;zc++){var Ec=k[zc];"-"!==Ec.G&&pb.push(Kb+Ec.frameId+"h"+Ec.G)}k=pb.join("p");k||(Ig&&(za(!0,"a",M),$d(!1)),k+=la+"$"+ug+"h-");k+="v"+(u||
    jd(M));fd("dtPC",k+"e0",void 0,Ma("ssc"))}function ve(k,u){void 0===u&&(u=document.cookie);var M=ba("dtPC",u);u=[];if(M&&"-"!==M){var la="";var pb=0;for(M=M.split("p");pb<M.length;pb++){var Kb=M[pb],zc=la,Ec=k;void 0===zc&&(zc="");la=va(Kb,"$");var Jc=va(Kb,"h");var od=va(Kb,"v"),Qe=va(Kb,"e");la=Kb.substring(la+1,Jc);Jc=-1!==od?Kb.substring(Jc+1,od):Kb.substring(Jc+1);zc||-1===od||(zc=-1!==Qe?Kb.substring(od+1,Qe):Kb.substring(od+1));Kb=null;Ec||(Ec=O(la.split("_")[0]),od=Wd()%kg,od<Ec&&(od+=kg),
    Ec=Ec+9E5>od);Ec&&(Kb={frameId:la,G:"-"===Jc?"-":O(Jc),visitId:""});la=zc;(Jc=Kb)&&u.push(Jc)}for(k=0;k<u.length;k++)u[k].visitId=la}return u}function me(k,u){var M=document.cookie;u=ve(u,M);for(var la=!1,pb=0;pb<u.length;pb++){var Kb=u[pb];Kb.frameId===ug&&(Kb.G=k,la=!0)}la||H(u,{frameId:ug,G:k,visitId:""});id(u,void 0,M)}function jd(k){return kd(k)||za(!0,"c",k)}function kd(k){if(Fd(k)<=Wd())return za(!0,"t",k);var u=r(k);if(!u)return za(!0,"c",k);var M=uj.exec(u);if(!M||3!==M.length||32!==M[1].length||
    isNaN(O(M[2])))return za(!0,"i",k);P("rxvisitid",u);return u}function we(k,u){var M=Wd();u=Fc(u).Hc;k&&(u=M);Xb(M+ki+"|"+u);Ab()}function Mf(k){var u="t"+(Wd()-Fd(k)),M=r(k),la=D();I(la,k);eb(la,u,M)}function r(k){var u,M;return null!==(M=null===(u=ve(!0,k)[0])||void 0===u?void 0:u.visitId)&&void 0!==M?M:aa("rxvisitid")}function D(){var k=Ld(32);k=k.replace(/[0-9]/g,function(u){u=.1*O(u);return String.fromCharCode(Math.floor(25*u+65))});return k+"-0"}function I(k,u){var M=ve(!1,u);id(M,k,u);P("rxvisitid",
    k);we(!0)}function ha(k,u,M){return za(u,M)}function ta(k,u,M){return za(k,u,M)}function za(k,u,M){k&&(vg=!0);k=r(M);M=D();I(M);eb(M,u,k);return M}function eb(k,u,M){if(r(document.cookie))for(var la=0,pb=Bi;la<pb.length;la++)(0,pb[la])(k,vg,u,M)}function hb(k){Bi.push(k)}function Ab(k){oh&&Yb(oh);oh=$b(Lb,Fd(k)-Wd())}function Lb(){var k=document.cookie;if(Fd(k)<=Wd())return z(Mf,[k]),!0;Kd(Ab);return!1}function Xb(k){fd("rxvt",k,void 0,Ma("ssc"));P("rxvt",k)}function xc(k,u){(u=ba(k,u))||(u=aa(k)||
    "");return u}function Uc(){var k=kd()||"";P("rxvisitid",k);k=xc("rxvt");Xb(k);Rc()}function Fc(k){var u={yd:0,Hc:0};if(k=xc("rxvt",k))try{var M=k.split("|");2===M.length&&(u.yd=parseInt(M[0],10),u.Hc=parseInt(M[1],10))}catch(la){}return u}function Fd(k){k=Fc(k);return Math.min(k.yd,k.Hc+Kh)}function Rd(k){ki=k}function ne(){var k=vg;vg=!1;return k}function Fe(){Lb()||we(!1)}function ee(k){try{if(v.localStorage)return v.localStorage.getItem(k)}catch(u){}return null}function bf(){var k=ba("rxVisitor");
    k&&45===(null===k||void 0===k?void 0:k.length)||(k=ee("rxVisitor")||aa("rxVisitor"),45!==(null===k||void 0===k?void 0:k.length)&&(Yi=!0,k=String(Wd()),k+=Ld(45-k.length)));of(k);return k}function of(k){if(Ma("dpvc")||Ma("pVO"))P("rxVisitor",k);else{var u=new Date;var M=u.getMonth()+Math.min(24,Math.max(1,Q("rvcl")));u.setMonth(M);z(Tc,["rxVisitor",k])}fd("rxVisitor",k,u,Ma("ssc"))}function ph(){return Yi}function Lh(k){var u=ba("rxVisitor");Cc("rxVisitor");U("rxVisitor");Bc("rxVisitor");wa("pVO",
    !0);of(u);k&&z(Tc,["dt-pVO","1"]);Uc()}function $g(){Bc("dt-pVO");Ma("pVO")&&(wa("pVO",!1),bf());U("rxVisitor");Uc()}function yf(k,u,M,la,pb){var Kb=document.createElement("script");Kb.setAttribute("src",k);u&&Kb.setAttribute("defer","defer");M&&(Kb.onload=M);la&&(Kb.onerror=la);pb&&Kb.setAttribute("id",pb);Kb.setAttribute("crossorigin","anonymous");k=document.getElementsByTagName("script")[0];k.parentElement.insertBefore(Kb,k)}function Nf(k,u){return Xe+"/"+(u||xd)+"_"+k+"_"+(Q("buildNumber")||v.dT_.version)+
    ".js"}function ah(){var k,u;try{null===(u=null===(k=v.MobileAgent)||void 0===k?void 0:k.incrementActionCount)||void 0===u?void 0:u.call(k)}catch(M){}}function wg(){var k,u=v.dT_;v.dT_=(k={},k.di=0,k.version="10233220201140653",k.cfg=u?u.cfg:"",k.iCE=u?Ua:function(){return navigator.cookieEnabled},k.ica=1,k.disabled=!1,k.overloadPrevention=!1,k.gAST=Cb,k.ww=ya,k.stu=oa,k.nw=Nb,k.apush=H,k.st=$b,k.si=ic,k.aBPSL=Vb,k.rBPSL=kc,k.gBPSL=dd,k.aBPSCC=Sa,k.gBPSCC=db,k.buildType="dynatrace",k.gSSV=aa,k.sSSV=P,k.rSSV=
    U,k.rvl=Bc,k.pn=O,k.iVSC=Nc,k.p3SC=xb,k.pLSC=ob,k.io=va,k.dC=Cc,k.sC=fd,k.esc=E,k.gSId=lc,k.gDtc=Jd,k.gSC=qc,k.sSC=Qd,k.gC=lb,k.cRN=wd,k.cRS=Ld,k.gEL=L,k.gEBTN=Pa,k.cfgO=w,k.pCfg=Gb,k.pCSAA=Z,k.cFHFAU=pc,k.sCD=N,k.bcv=Ma,k.ncv=Q,k.scv=fa,k.stcv=wa,k.rplC=Za,k.cLSCK=wb,k.gFId=Ve,k.gBAU=Nf,k.iS=yf,k.eWE=Kd,k.oEIE=rc,k.oEIEWA=z,k.eA=Dc,k.dA=Ic,k.iNV=ph,k.gVID=bf,k.dPV=Lh,k.ePV=$g,k.sVIdUP=$d,k.sVTT=Rd,k.sVID=I,k.rVID=kd,k.gVI=jd,k.gNVIdN=ta,k.gNVId=ha,k.gARnVF=ne,k.cAUV=Fe,k.uVT=we,k.aNVL=hb,k.gPC=ve,
    k.cPC=me,k.sPC=id,k.clB=vc,k.ct=Yb,k.aRI=Bb,k.iXB=ec,k.gXBR=tb,k.sXBR=nb,k.de=S,k.cCL=Qa,k.iEC=ah,k.rnw=fb,k.gto=xa,k.ael=qa,k.rel=Ha,k.sup=Ya,k.cuel=Ib,k.iAEPOO=J,k.iSM=qb,k.aIOf=ma,k.gxwp=V,k.iIO=R,k.prm=ia,k.cI=Zc,k.gidi=Oa,k.iDCV=F,k.gCF=ba,k.gPSMB=q,k.lvl=ee,k)}function G(){Kd(function(){if(!Jd()){var k=-1*wd(2,99),u=Ld(32),M=Q("ssv");Qd(4===M?"v_4_srv_"+String(k).replace("-","-2D")+"_sn_"+u:3===M?"=3=srv="+k+"=sn="+u:k+"$"+u)}})}var B="undefined"!==typeof window?window:self,v="undefined"!==
    typeof window?window:self,Aa,cb,zb=setTimeout;ja.prototype["catch"]=function(k){return this.then(null,k)};ja.prototype.then=function(k,u){var M=new this.constructor(Y);ua(this,new W(k,u,M));return M};ja.prototype["finally"]=function(k){var u=this.constructor;return this.then(function(M){return u.resolve(k()).then(function(){return M})},function(M){return u.resolve(k()).then(function(){return u.reject(M)})})};ja.all=function(k){return new ja(function(u,M){function la(Ec,Jc){try{if(Jc&&("object"===
    typeof Jc||"function"===typeof Jc)){var od=Jc.then;if("function"===typeof od){od.call(Jc,function(Qe){la(Ec,Qe)},M);return}}pb[Ec]=Jc;0===--Kb&&u(pb)}catch(Qe){M(Qe)}}if(!k||"undefined"===typeof k.length)return M(new TypeError("Promise.all accepts an array"));var pb=Array.prototype.slice.call(k);if(0===pb.length)return u([]);for(var Kb=pb.length,zc=0;zc<pb.length;zc++)la(zc,pb[zc])})};ja.allSettled=function(k){return new this(function(u,M){function la(zc,Ec){if(Ec&&("object"===typeof Ec||"function"===
    typeof Ec)){var Jc=Ec.then;if("function"===typeof Jc){Jc.call(Ec,function(od){la(zc,od)},function(od){pb[zc]={status:"rejected",reason:od};0===--Kb&&u(pb)});return}}pb[zc]={status:"fulfilled",value:Ec};0===--Kb&&u(pb)}if(!k||"undefined"===typeof k.length)return M(new TypeError(typeof k+" "+k+" is not iterable(cannot read property Symbol(Symbol.iterator))"));var pb=Array.prototype.slice.call(k);if(0===pb.length)return u([]);var Kb=pb.length;for(M=0;M<pb.length;M++)la(M,pb[M])})};ja.resolve=function(k){return k&&
    "object"===typeof k&&k.constructor===ja?k:new ja(function(u){u(k)})};ja.reject=function(k){return new ja(function(u,M){M(k)})};ja.race=function(k){return new ja(function(u,M){if(!k||"undefined"===typeof k.length)return M(new TypeError("Promise.race accepts an array"));for(var la=0,pb=k.length;la<pb;la++)ja.resolve(k[la]).then(u,M)})};ja.Aa="function"===typeof setImmediate&&function(k){setImmediate(k)}||function(k){zb(k,0)};ja.$a=function(k){"undefined"!==typeof console&&console&&console.warn("Possible Unhandled Promise Rejection:",
    k)};var Jb=ja,Tb={"!":"%21","~":"%7E","*":"%2A","(":"%28",")":"%29","'":"%27",$:"%24",";":"%3B",",":"%2C"},Ob,cc,Hc,Dd,qd=v.attachEvent,Id=v.Worker,Yc=Id&&Id.prototype.addEventListener,ld=[],If=["touchstart","touchend","scroll"],He,$c,ef="abort getAllResponseHeaders getResponseHeader open overrideMimeType send setRequestHeader".split(" "),qe,Mc,md,Bd,ye=(Bd={},Bd.l="Lax",Bd.s="Strict",Bd.n="None",Bd),uc={},zd,ke=v.Worker,af=v.Blob,Xi=v.URL&&v.URL.createObjectURL,Oe,Tf,nh,Zg,Pe=!1,re,nf=[],ff=[],Jh,
    Hg,Jf={},Wd,le=!1,Ed=[],ue=[],tg=[],Kf,Of,ug,kg=6E8,Lf=[],We=[],Ig=!1,uj=/([A-Z]+)-([0-9]+)/,Bi=[],ki,Kh,vg=!1,oh,Yi=!1,Ci,Xe,xd;(function(k){var u,M;k=k||0>(null===(u=navigator.userAgent)||void 0===u?void 0:u.indexOf("RuxitSynthetic"));if(!v.dT_||!v.dT_.cfg||"string"!==typeof v.dT_.cfg||"initialized"in v.dT_&&v.dT_.initialized)null===(M=v.console)||void 0===M?void 0:M.log("InitConfig not found or agent already initialized! This is an injection issue."),v.dT_&&(v.dT_.di=3);else if(k)try{var la;ia();
    var pb;He=v.XMLHttpRequest;$c=v.ActiveXObject;var Kb=null===(pb=v.XMLHttpRequest)||void 0===pb?void 0:pb.prototype;if(Kb)for(qe={},u=0,M=ef;u<M.length;u++){var zc=M[u];void 0!==Kb[zc]&&(qe[zc]=Kb[zc])}Ob=v.addEventListener;cc=v.removeEventListener;Hc=v.document.addEventListener;Dd=v.document.removeEventListener;nh=v.setTimeout;Zg=v.setInterval;Pe||(Oe=v.clearTimeout,Tf=v.clearInterval);var Ec=Ua?Ua():navigator.cookieEnabled,Jc=1===xb(ba("dtAdkSettings")||(null===(la=Hg)||void 0===la?void 0:la.getItem("dtAdkSettings"))||
    "").cc;Qa();if(!(!Ec||Jc?0:"complete"!==document.readyState||v.performance&&v.performance.timing))throw Error("Error during initCode initialization");wg();try{Hg=v.localStorage}catch(sa){}Ac();Jh=Wd();re=[];ff=[];Jf={};if(!Pe){v.clearTimeout=Qb(Oe);v.clearInterval=Qb(Tf);Pe=!0;try{zd=v.sessionStorage}catch(sa){}}var od=Math.random(),Qe=Math.random();Of=0!==od&&0!==Qe&&od!==Qe;if(-1!==va(navigator.userAgent,"Googlebot")){var oe=performance.getEntriesByType("navigation")[0];la=1;if(oe){for(var Pf in oe){var ze=
    oe[Pf];"number"===typeof ze&&ze&&(la=1===la?ze:la+ze)}var Qf=Math.floor(1E4*la)}else Qf=la;Kf=sc(Qf)}else Of?Kf=Math.random:Kf=sc(Wd());ug=Jh%kg+"_"+O(wd(0,1E3)+"");var Ca;md=(Ca={},Ca.ade="",Ca.aew=!0,Ca.apn="",Ca.agentLocation="",Ca.agentUri="",Ca.app="",Ca.async=!1,Ca.ase=!1,Ca.auto=!1,Ca.bp1=!1,Ca.bp2=!1,Ca.bp=1,Ca.bisaoi=!1,Ca.bisCmE="",Ca.bs=!1,Ca.buildNumber=0,Ca.csprv=!0,Ca.cepl=16E3,Ca.cls=!0,Ca.ccNcss=!1,Ca.cg=!1,Ca.coo=!1,Ca.cooO=!1,Ca.cssm="0",Ca.cors=!1,Ca.csu="",Ca.cuc="",Ca.cce=!1,
    Ca.cux=!1,Ca.dataDtConfig="",Ca.debugName="",Ca.dvl=500,Ca.dASXH=!1,Ca.disableCookieManager=!1,Ca.disableLogging=!1,Ca.dmo=!1,Ca.doel=!1,Ca.dpch=!1,Ca.dpvc=!1,Ca.disableXhrFailures=!1,Ca.domain="",Ca.domainOverride="",Ca.doNotDetect="",Ca.ds=!0,Ca.dsndb=!1,Ca.dsa=!1,Ca.dsss=!1,Ca.dssv=!0,Ca.earxa=!0,Ca.exp=!1,Ca.eni=!0,Ca.erjdw=!0,Ca.expw=!1,Ca.instr="",Ca.evl="",Ca.extblacklist="",Ca.euf=!1,Ca.fau=!0,Ca.fa=!1,Ca.fvdi=!1,Ca.featureHash="",Ca.hvt=216E5,Ca.ffi=!1,Ca.imm=!1,Ca.ign="",Ca.iub="",Ca.iqvn=
    !1,Ca.initializedModules="",Ca.lastModification=0,Ca.lupr=!0,Ca.lab=!1,Ca.legacy=!1,Ca.lt=!0,Ca.mb="",Ca.md="",Ca.mdp="",Ca.mdl="",Ca.mcepsl=100,Ca.mdn=5E3,Ca.mhl=4E3,Ca.mpl=1024,Ca.mmds=2E4,Ca.msl=3E4,Ca.bismepl=2E3,Ca.mel=200,Ca.mepp=10,Ca.moa=30,Ca.mrt=3,Ca.ntd=!1,Ca.ncw=!1,Ca.oat=180,Ca.ote=!1,Ca.owasp=!1,Ca.pcl=20,Ca.pt=!0,Ca.perfbv=1,Ca.prfSmpl=0,Ca.pVO=!1,Ca.peti=!1,Ca.raxeh=!0,Ca.rdnt=0,Ca.nosr=!0,Ca.reportUrl="dynaTraceMonitor",Ca.rid="",Ca.ridPath="",Ca.rpid="",Ca.rcdec=12096E5,Ca.rtl=0,
    Ca.rtp=2,Ca.rtt=1E3,Ca.rtu=200,Ca.restoreTimeline=!1,Ca.rvcl=24,Ca.sl=100,Ca.ssc=!1,Ca.svNB=!1,Ca.srad=!0,Ca.srbbv=1,Ca.srbw=!0,Ca.srmr=100,Ca.srms="1,1,,,",Ca.srsr=1E5,Ca.srtbv=3,Ca.srtd=1,Ca.srtr=500,Ca.srvr="",Ca.srvi=0,Ca.srwo=!1,Ca.srre="",Ca.srxcss=!0,Ca.srxicss=!0,Ca.srif=!1,Ca.srmrc=!1,Ca.srsdom=!1,Ca.srcss=!0,Ca.srmcrl=1,Ca.srmcrv=10,Ca.ssv=1,Ca.st=3E3,Ca.spc="",Ca.syntheticConfig=!1,Ca.tal=0,Ca.tp="500,50,3",Ca.tt=100,Ca.tvc=3E3,Ca.exteventsoff=!1,Ca.uxdce=!1,Ca.uxdcw=1500,Ca.uxrgce=!0,
    Ca.uxrgcm="100,25,300,3;100,25,300,3",Ca.uam=!1,Ca.uana="data-dtname,data-dtName",Ca.uanpi=0,Ca.pui=!1,Ca.usrvd=!0,Ca.vrt=!1,Ca.vcfi=!0,Ca.vcit=1E3,Ca.vct=50,Ca.vcx=50,Ca.vscl=0,Ca.vncm=1,Ca.xb="",Ca.chw="",Ca.xt=0,Ca.xhb="",Ca);a:{var Md=v.dT_.cfg;uc={reportUrl:"dynaTraceMonitor",initializedModules:"",csu:"dtagent",dataDtConfig:"string"===typeof Md?Md:""};v.dT_.cfg=uc;uc.csu="ruxitagentjs";var cf=uc.dataDtConfig;cf&&-1===va(cf,"#CONFIGSTRING")&&(Z(cf,uc),Eb("domain"),Eb("auto"),Eb("app"),pc(uc));
    var Uf=Pa("script"),li=L(Uf),Ie=-1===va(uc.dataDtConfig||"","#CONFIGSTRING")?uc:null;if(0<li)for(Qf=0;Qf<li;Qf++)b:{oe=void 0;var yc=Uf[Qf];Pf=Ie;if(yc.attributes){var bh=uc.csu+"_bootstrap.js";ze=/.*\/jstag\/.*\/.*\/(.*)_bs(_dbg)?.js$/;Ca=Pf;var fe=yc.src,Od=null===fe||void 0===fe?void 0:fe.indexOf(bh),Sc=yc.attributes.getNamedItem("data-dtconfig");if(Sc){Md=void 0;cf=fe;var lg=Sc.value;la={};uc.legacy="1";Kb=/([a-zA-Z]*)_([a-zA-Z_0-9]*)_([0-9]+)/g;cf&&(Md=Kb.exec(cf),null===Md||void 0===Md?0:Md.length)&&
    (la.csu=Md[1],la.featureHash=Md[2],la.agentLocation=cf.substr(0,va(cf,Md[1])-1),la.buildNumber=Md[3]);if(lg){Z(lg,la,!0);var ae=la.agentUri;!cf&&ae&&(Md=Kb.exec(ae),null===Md||void 0===Md?0:Md.length)&&(la.csu=Md[1])}Fb(la);oe=la;if(!Pf)Ca=oe;else if(!oe.syntheticConfig){Ie=oe;break b}}oe||(oe=uc);if(0<Od){var mg=Od+bh.length+5;oe.app=fe.length>mg?fe.substr(mg):"Default%20Application"}else if(fe){var ud=ze.exec(fe);ud&&(oe.app=ud[1])}Ie=Ca}else Ie=Pf}if(Ie)for(var pf in Ie)Object.prototype.hasOwnProperty.call(Ie,
    pf)&&(Uf=pf,uc[Uf]=Ie[Uf]);var Ae=wb();try{var qf=(Ie=Hg)&&Ie.getItem(Ae);if(qf){var Jg=Gb(qf),be=Z(Jg.config||""),Kg=uc.lastModification||"0",qh=O((be.lastModification||Jg.lastModification||"0").substr(0,13)),dg="string"===typeof Kg?O(Kg.substr(0,13)):Kg;if(!Kg||qh>=dg)if(be.csu=Jg.name,be.featureHash=Jg.featureHash,be.agentUri&&pc(be),N(be,!0),ec(be),Bb(be),qh>(uc.lastModification||0)){var Mh=uc.auto,zf=uc.legacy;uc=Za(be);uc.auto=Mh;uc.legacy=zf}}}catch(sa){}N(uc);try{var ce=uc.ign;if(ce&&(new RegExp(ce)).test(v.location.href)){document.dT_=
    v.dT_=void 0;var Je=!1;break a}}catch(sa){}if(qb()){var Af=navigator.userAgent,gf=Af.lastIndexOf("RuxitSynthetic");if(-1===gf)var Bf={};else{var rf=Af.substring(gf+14);if(-1===va(rf," c"))Bf={};else{Ae={};qf=0;for(var Nh=rf.split(" ");qf<Nh.length;qf++){var Zi=Nh[qf];if("c"===Zi.charAt(0)){var Di=Zi.substr(1),Vf=Di.indexOf("="),$i=Di.substring(0,Vf),Ei=Di.substring(Vf+1);$i&&Ei&&(Ae[$i]=Ei)}}Bf=Ae}}rf=void 0;for(rf in Bf)Object.prototype.hasOwnProperty.call(Bf,rf)&&Bf[rf]&&(uc[rf]=Bf[rf]);Za(uc)}Je=
    !0}if(!Je)throw Error("Error during config initialization");Xd();try{Ci=v.dT_.disabled||!!aa("dtDisabled")}catch(sa){}var Oh;if(!(Oh=fa("agentLocation")))a:{var aj=fa("agentUri");if(aj||document.currentScript){var Wf=aj||document.currentScript.src;if(Wf){Je=Wf;var vj=-1===va(Je,"_bs")&&-1===va(Je,"_bootstrap")&&-1===va(Je,"_complete")?1:2,Cf=Wf.lastIndexOf("/");for(Je=0;Je<vj&&-1!==Cf;Je++)Wf=Wf.substr(0,Cf),Cf=Wf.lastIndexOf("/");Oh=Wf;break a}}var Re=location.pathname;Oh=Re.substr(0,Re.lastIndexOf("/"))}Xe=
    Oh;xd=fa("csu")||"ruxitagentjs";"true"===ba("dtUseDebugAgent")&&0>xd.indexOf("dbg")&&(xd=fa("debugName")||xd+"dbg");if(!Ma("auto")&&!Ma("legacy")&&!Ci){var Ph=fa("agentUri")||Nf(fa("featureHash")),A;if(!(A=Ma("async")||"complete"===document.readyState)){var K=v.navigator.userAgent,da=K.indexOf("MSIE ");A=0<da?9>=parseInt(K.substring(da+5,K.indexOf(".",da)),10):!1}A?yf(Ph,Ma("async"),void 0,void 0,"dtjsagent"):(document.write('<script id="dtjsagentdw" type="text/javascript" src="'+Ph+'">\x3c/script>'),
    document.getElementById("dtjsagentdw")||yf(Ph,Ma("async"),void 0,void 0,"dtjsagent"))}ba("dtCookie")&&wa("cooO",!0);G();wa("pVO",!!ee("dt-pVO"));Kd(bf);ki=18E5;Kh=Q("hvt")||216E5;z(me,[1]);We=[];Lf="dtCookie dtLatC rxvt dtAdk dtAdkSettings dtPC".split(" ");if(Ma("cg"))try{Ee(Object.getOwnPropertyDescriptor(Document.prototype,"cookie")||Object.getOwnPropertyDescriptor(HTMLDocument.prototype,"cookie"))}catch(sa){}}catch(sa){try{delete v.dT_}catch(ib){v.dT_=void 0}Qa()&&v.console.log("JsAgent initCode initialization failed!")}})(!1)})()})();
`
    document.body.prepend(script)

    return () => {
      document.body.removeChild(script)
    }
  }, [])
}

export default useScript
